apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:    
      {{- toYaml .Values.ingress.apirutas | nindent 6 }}