# Default values for plantilla.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: #{ContainersImage.replicaCount}#

image:
  repository: #{ContainersImage.Repository}#/company.yourcompany.ms.#{nameapi}#
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: #{Namespace.Ambiente}#

imagePullSecrets: #{ContainersImage.PullSecrets}#
nameAzureIdentity: #{AzureIdentity.Name}#

service:
  type: ClusterIP
  port: #{ContainersImage.port}#
  targetPort: #{ContainersImage.targetPort}#

ingress:
  name: #{Ingress.Name}#-yourcompany#{nameapi}#-#{Namespace.Ambiente}#
  hostname: yourcompany-#{Namespace.Ambiente}#.yourcompany.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/use-regex: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300000"
  tls:
    - hosts:
      - yourcompany-#{Namespace.Ambiente}#.yourcompany.com
      secretName: #{SSLCertificate.SecretName}#
  apirutas:
    paths:                           
    - path: #{pathapi}#
      pathType: Prefix
      backend:
        service:
          name: srv-#{nameapi}#
          port: 
            number: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "deploy"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

fullname: #{nameapi}#
selectorLabels: #{nameapi}#
